### ISSUE TITLE
TinyMCE not respecting mgr language

### ISSUE THREAD

**Issue by avoronkin** [splittingred/TinyMCE#1]
Tinymce does not switch to manager language.
MODx Revolution 2.0.0-rc-3 rev7048
tinymce-4.0.0-rc3

There hardcoded en.js in plugin code at line 40:
$modx->regClientStartupScript($tiny->config['assets_url'].'jscripts/tiny_mce/langs/en.js');

Only the English language files for themes and plugins in

assets/components/tinymce/jscripts/tiny_mce/themes/advanced/langs
assets/components/tinymce/jscripts/tiny_mce/plugins/

I think translation for themes and plugins can be taken from the distribution for Evolution

**Comment by splittingred** [comment]
Fixed bug in 4.0.0-pl

**Comment by enigmatic-user** [comment]
As reported in http://bugs.modx.com/browse/TINYMCE-78 (is the project still maintained that issue tracker? If not, is there a way to make it read-only?), switching TinyMCE to other languages via the manager_language system setting still doesn't work in version 4.1.0-rc1. Two changes have to be made:

#### 1) /assets/components/tinymce/tinymce.panel.js, line 26:

```
,language: MODx.config.manager_language
```

has to be changed to

```
,language: MODx.config['manager_language']
```

There's another line in this file (line 11) that uses this notation:

```
,browserUrl: MODx.config.manager_url+'?a='+MODx.action['browser']
```

I guess this has to be changed, too, but I have to admit that I have no idea what this is used for. This hasn't anything to do with this bug.

#### 2) /core/components/tinymce/tinymce.plugin.php, add e. g. in line 94:

```
'language' => $this->modx->getOption('manager_language',$this->properties,'de'),
```
